/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
future: {
    v2_errorBoundary: true,
  },
  ignoredRouteFiles: ["**/.*"],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  serverDependenciesToBundle: [
    "marked",
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    /^unist.*/,
    /^hast.*/,
    /^bail.*/,
    /^trough.*/,
    /^mdast.*/,
    /^micromark.*/,
    /^decode.*/,
    /^character.*/,
    /^property.*/,
    /^space.*/,
    /^comma.*/,
    /^react-markdown$/,
    /^vfile.*/,
    "trim-lines",
    "lowlight",
    "html-void-elements",
    "web-namespaces",
    "zwitch",
    "ccount",
    "markdown-table",
    "fault",
    "is-plain-obj",
    "escape-string-regexp",
  ],
};
